// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Js_math = require("bs-platform/lib/js/js_math.js");
var Belt_Int = require("bs-platform/lib/js/belt_Int.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function isNotempty(str) {
  return str !== "";
}

function calcFuel(mass) {
  var match = Belt_Int.fromString(mass);
  if (match !== undefined) {
    return Js_math.floor(match / 3.0) - 2 | 0;
  }
  
}

function calcTotalFuel(total, fuel) {
  return fuel + total | 0;
}

console.log(List.fold_left(calcTotalFuel, 0, List.map(Belt_Option.getExn, List.filter(Belt_Option.isSome)(List.map(calcFuel, List.filter(isNotempty)($$Array.to_list(Fs.readFileSync("../inputs/day1.txt", "utf8").split("\n"))))))));

exports.isNotempty = isNotempty;
exports.calcFuel = calcFuel;
exports.calcTotalFuel = calcTotalFuel;
/*  Not a pure module */
